### ISSUE TITLE
I refresh web it always throws 401 unauthorized,even if I login many times

### ISSUE THREAD

**Issue by shiningstarts** [codecov/enterprise-resources#3]
enterprise version: v4.3.9 (e9fe30a)

**Comment by brightest-dazes** [comment]
Today is a new day!

**Comment by brightest-dazes** [comment]
I need help with fixing the 401

**Comment by hootener** [comment]
Closing this issue as the resources provided here are intended to be used with Codecov Enterprise version 4.4.5 and greater.

If you're deploying a new installation of Codecov Enterprise, I recommend using our most recent version, 4.4.7, and the docs: https://docs.codecov.io/docs/install-guide
